services:
  - type: web
    name: kcds-visit-ur-destiny
    runtime: node
    repo: https://github.com/kcdhanunjay70/kcds-visit-ur-destiny
    branch: main
    buildCommand: npm install
    startCommand: npm start
    pullRequestPreviewsEnabled: true
