services:
  - type: web
    name: kcds-visit-ur-destiny
    runtime: static
    repo: https://github.com/kcdhanunjay70/kcds-visit-ur-destiny
    branch: main
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
